/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gr4vy.sdk;

import static com.gr4vy.sdk.operations.Operations.RequestOperation;

import com.gr4vy.sdk.models.operations.ListBuyerGiftCardsRequest;
import com.gr4vy.sdk.models.operations.ListBuyerGiftCardsRequestBuilder;
import com.gr4vy.sdk.models.operations.ListBuyerGiftCardsResponse;
import com.gr4vy.sdk.operations.ListBuyerGiftCards;
import com.gr4vy.sdk.utils.Headers;
import com.gr4vy.sdk.utils.Options;
import java.util.Optional;


public class BuyersGiftCards {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;
    private final AsyncBuyersGiftCards asyncSDK;

    BuyersGiftCards(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
        this.asyncSDK = new AsyncBuyersGiftCards(this, sdkConfiguration);
    }

    /**
     * Switches to the async SDK.
     * 
     * @return The async SDK
     */
    public AsyncBuyersGiftCards async() {
        return asyncSDK;
    }

    /**
     * List gift cards for a buyer
     * 
     * <p>List all the stored gift cards for a specific buyer.
     * 
     * @return The call builder
     */
    public ListBuyerGiftCardsRequestBuilder list() {
        return new ListBuyerGiftCardsRequestBuilder(sdkConfiguration);
    }

    /**
     * List gift cards for a buyer
     * 
     * <p>List all the stored gift cards for a specific buyer.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListBuyerGiftCardsResponse list(ListBuyerGiftCardsRequest request) {
        return list(request, Optional.empty());
    }

    /**
     * List gift cards for a buyer
     * 
     * <p>List all the stored gift cards for a specific buyer.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param options additional options
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public ListBuyerGiftCardsResponse list(ListBuyerGiftCardsRequest request, Optional<Options> options) {
        RequestOperation<ListBuyerGiftCardsRequest, ListBuyerGiftCardsResponse> operation
              = new ListBuyerGiftCards.Sync(sdkConfiguration, options, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
