/*
 * Gr4vy API
 * Welcome to the Gr4vy API reference documentation. Our API is still very much a work in product and subject to change.
 *
 * The version of the OpenAPI document: 1.1.0-beta
 * Contact: code@gr4vy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gr4vy.api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.gr4vy.api.model.GiftCardServiceCreateRequestFields;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Request body for activating a gift card service.
 */
@ApiModel(description = "Request body for activating a gift card service.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class GiftCardServiceCreateRequest {
  public static final String SERIALIZED_NAME_GIFT_CARD_SERVICE_DEFINITION_ID = "gift_card_service_definition_id";
  @SerializedName(SERIALIZED_NAME_GIFT_CARD_SERVICE_DEFINITION_ID)
  private String giftCardServiceDefinitionId;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "display_name";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private List<GiftCardServiceCreateRequestFields> fields = new ArrayList<GiftCardServiceCreateRequestFields>();

  public static final String SERIALIZED_NAME_ACTIVE = "active";
  @SerializedName(SERIALIZED_NAME_ACTIVE)
  private Boolean active = true;


  public GiftCardServiceCreateRequest giftCardServiceDefinitionId(String giftCardServiceDefinitionId) {
    
    this.giftCardServiceDefinitionId = giftCardServiceDefinitionId;
    return this;
  }

   /**
   * The ID of the gift card service to use.
   * @return giftCardServiceDefinitionId
  **/
  @ApiModelProperty(example = "qwikcilver-gift-card", required = true, value = "The ID of the gift card service to use.")

  public String getGiftCardServiceDefinitionId() {
    return giftCardServiceDefinitionId;
  }


  public void setGiftCardServiceDefinitionId(String giftCardServiceDefinitionId) {
    this.giftCardServiceDefinitionId = giftCardServiceDefinitionId;
  }


  public GiftCardServiceCreateRequest displayName(String displayName) {
    
    this.displayName = displayName;
    return this;
  }

   /**
   * A custom name for the service. This will be shown in the Admin UI.
   * @return displayName
  **/
  @ApiModelProperty(example = "Qwikcilver UK", required = true, value = "A custom name for the service. This will be shown in the Admin UI.")

  public String getDisplayName() {
    return displayName;
  }


  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  public GiftCardServiceCreateRequest fields(List<GiftCardServiceCreateRequestFields> fields) {
    
    this.fields = fields;
    return this;
  }

  public GiftCardServiceCreateRequest addFieldsItem(GiftCardServiceCreateRequestFields fieldsItem) {
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * A list of fields, each containing a key-value pair for each field defined by the definition for this gift card service.
   * @return fields
  **/
  @ApiModelProperty(required = true, value = "A list of fields, each containing a key-value pair for each field defined by the definition for this gift card service.")

  public List<GiftCardServiceCreateRequestFields> getFields() {
    return fields;
  }


  public void setFields(List<GiftCardServiceCreateRequestFields> fields) {
    this.fields = fields;
  }


  public GiftCardServiceCreateRequest active(Boolean active) {
    
    this.active = active;
    return this;
  }

   /**
   * Defines if this service is currently active or not.
   * @return active
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "Defines if this service is currently active or not.")

  public Boolean getActive() {
    return active;
  }


  public void setActive(Boolean active) {
    this.active = active;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GiftCardServiceCreateRequest giftCardServiceCreateRequest = (GiftCardServiceCreateRequest) o;
    return Objects.equals(this.giftCardServiceDefinitionId, giftCardServiceCreateRequest.giftCardServiceDefinitionId) &&
        Objects.equals(this.displayName, giftCardServiceCreateRequest.displayName) &&
        Objects.equals(this.fields, giftCardServiceCreateRequest.fields) &&
        Objects.equals(this.active, giftCardServiceCreateRequest.active);
  }

  @Override
  public int hashCode() {
    return Objects.hash(giftCardServiceDefinitionId, displayName, fields, active);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GiftCardServiceCreateRequest {\n");
    sb.append("    giftCardServiceDefinitionId: ").append(toIndentedString(giftCardServiceDefinitionId)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

