/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.github.gr4vy.gr4vy_java.models.operations;

import com.github.gr4vy.gr4vy_java.models.components.PaymentServiceUpdate;
import com.github.gr4vy.gr4vy_java.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import org.openapitools.jackson.nullable.JsonNullable;

public class CreatePaymentServiceRequestBuilder {

    private String paymentServiceId;
    private JsonNullable<String> xGr4vyMerchantAccountId = JsonNullable.undefined();
    private PaymentServiceUpdate paymentServiceUpdate;
    private final SDKMethodInterfaces.MethodCallCreatePaymentService sdk;

    public CreatePaymentServiceRequestBuilder(SDKMethodInterfaces.MethodCallCreatePaymentService sdk) {
        this.sdk = sdk;
    }

    public CreatePaymentServiceRequestBuilder paymentServiceId(String paymentServiceId) {
        Utils.checkNotNull(paymentServiceId, "paymentServiceId");
        this.paymentServiceId = paymentServiceId;
        return this;
    }

    public CreatePaymentServiceRequestBuilder xGr4vyMerchantAccountId(String xGr4vyMerchantAccountId) {
        Utils.checkNotNull(xGr4vyMerchantAccountId, "xGr4vyMerchantAccountId");
        this.xGr4vyMerchantAccountId = JsonNullable.of(xGr4vyMerchantAccountId);
        return this;
    }

    public CreatePaymentServiceRequestBuilder xGr4vyMerchantAccountId(JsonNullable<String> xGr4vyMerchantAccountId) {
        Utils.checkNotNull(xGr4vyMerchantAccountId, "xGr4vyMerchantAccountId");
        this.xGr4vyMerchantAccountId = xGr4vyMerchantAccountId;
        return this;
    }

    public CreatePaymentServiceRequestBuilder paymentServiceUpdate(PaymentServiceUpdate paymentServiceUpdate) {
        Utils.checkNotNull(paymentServiceUpdate, "paymentServiceUpdate");
        this.paymentServiceUpdate = paymentServiceUpdate;
        return this;
    }

    public CreatePaymentServiceResponse call() throws Exception {

        return sdk.update(
            paymentServiceId,
            xGr4vyMerchantAccountId,
            paymentServiceUpdate);
    }
}
