/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.github.gr4vy.gr4vy_java.models.operations;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.github.gr4vy.gr4vy_java.models.components.BaseModel;
import com.github.gr4vy.gr4vy_java.models.components.CheckoutSessionUpdate;
import com.github.gr4vy.gr4vy_java.utils.OneOfDeserializer;
import com.github.gr4vy.gr4vy_java.utils.TypedObject;
import com.github.gr4vy.gr4vy_java.utils.Utils.JsonShape;
import com.github.gr4vy.gr4vy_java.utils.Utils.TypeReferenceWithShape;
import com.github.gr4vy.gr4vy_java.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.List;
import java.util.Objects;

@JsonDeserialize(using = CreateCheckoutSessionBody._Deserializer.class)
public class CreateCheckoutSessionBody {

    @JsonValue
    private TypedObject value;
    
    private CreateCheckoutSessionBody(TypedObject value) {
        this.value = value;
    }

    public static CreateCheckoutSessionBody of(CheckoutSessionUpdate value) {
        Utils.checkNotNull(value, "value");
        return new CreateCheckoutSessionBody(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<CheckoutSessionUpdate>(){}));
    }

    public static CreateCheckoutSessionBody of(List<BaseModel> value) {
        Utils.checkNotNull(value, "value");
        return new CreateCheckoutSessionBody(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<List<BaseModel>>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code com.github.gr4vy.gr4vy_java.models.components.CheckoutSessionUpdate}</li>
     * <li>{@code java.util.List<com.github.gr4vy.gr4vy_java.models.components.BaseModel>}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateCheckoutSessionBody other = (CreateCheckoutSessionBody) o;
        return Objects.deepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends OneOfDeserializer<CreateCheckoutSessionBody> {

        public _Deserializer() {
            super(CreateCheckoutSessionBody.class, false,
                  TypeReferenceWithShape.of(new TypeReference<List<BaseModel>>() {}, JsonShape.DEFAULT),
                  TypeReferenceWithShape.of(new TypeReference<CheckoutSessionUpdate>() {}, JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateCheckoutSessionBody.class,
                "value", value);
    }
 
}

