/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.github.gr4vy.gr4vy_java.models.operations;

import com.github.gr4vy.gr4vy_java.utils.Utils;
import java.lang.Exception;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;

public class CreatePaymentServiceDefinitionSessionRequestBuilder {

    private String paymentServiceDefinitionId;
    private Map<String, Object> requestBody = new HashMap<>();
    private final SDKMethodInterfaces.MethodCallCreatePaymentServiceDefinitionSession sdk;

    public CreatePaymentServiceDefinitionSessionRequestBuilder(SDKMethodInterfaces.MethodCallCreatePaymentServiceDefinitionSession sdk) {
        this.sdk = sdk;
    }

    public CreatePaymentServiceDefinitionSessionRequestBuilder paymentServiceDefinitionId(String paymentServiceDefinitionId) {
        Utils.checkNotNull(paymentServiceDefinitionId, "paymentServiceDefinitionId");
        this.paymentServiceDefinitionId = paymentServiceDefinitionId;
        return this;
    }

    public CreatePaymentServiceDefinitionSessionRequestBuilder requestBody(Map<String, Object> requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }

    public CreatePaymentServiceDefinitionSessionResponse call() throws Exception {

        return sdk.session(
            paymentServiceDefinitionId,
            requestBody);
    }
}
