/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.github.gr4vy.gr4vy_java.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.github.gr4vy.gr4vy_java.models.components.PaymentServiceDefinition;
import com.github.gr4vy.gr4vy_java.utils.Response;
import com.github.gr4vy.gr4vy_java.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Objects;
import java.util.Optional;

public class GetPaymentServiceDefinitionResponse implements Response {

    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * Successful Response
     */
    private Optional<? extends PaymentServiceDefinition> paymentServiceDefinition;

    @JsonCreator
    public GetPaymentServiceDefinitionResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends PaymentServiceDefinition> paymentServiceDefinition) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(paymentServiceDefinition, "paymentServiceDefinition");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.paymentServiceDefinition = paymentServiceDefinition;
    }
    
    public GetPaymentServiceDefinitionResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse, Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * Successful Response
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PaymentServiceDefinition> paymentServiceDefinition() {
        return (Optional<PaymentServiceDefinition>) paymentServiceDefinition;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * HTTP response content type for this operation
     */
    public GetPaymentServiceDefinitionResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public GetPaymentServiceDefinitionResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public GetPaymentServiceDefinitionResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * Successful Response
     */
    public GetPaymentServiceDefinitionResponse withPaymentServiceDefinition(PaymentServiceDefinition paymentServiceDefinition) {
        Utils.checkNotNull(paymentServiceDefinition, "paymentServiceDefinition");
        this.paymentServiceDefinition = Optional.ofNullable(paymentServiceDefinition);
        return this;
    }

    /**
     * Successful Response
     */
    public GetPaymentServiceDefinitionResponse withPaymentServiceDefinition(Optional<? extends PaymentServiceDefinition> paymentServiceDefinition) {
        Utils.checkNotNull(paymentServiceDefinition, "paymentServiceDefinition");
        this.paymentServiceDefinition = paymentServiceDefinition;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetPaymentServiceDefinitionResponse other = (GetPaymentServiceDefinitionResponse) o;
        return 
            Objects.deepEquals(this.contentType, other.contentType) &&
            Objects.deepEquals(this.statusCode, other.statusCode) &&
            Objects.deepEquals(this.rawResponse, other.rawResponse) &&
            Objects.deepEquals(this.paymentServiceDefinition, other.paymentServiceDefinition);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            contentType,
            statusCode,
            rawResponse,
            paymentServiceDefinition);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetPaymentServiceDefinitionResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "paymentServiceDefinition", paymentServiceDefinition);
    }
    
    public final static class Builder {
 
        private String contentType;
 
        private Integer statusCode;
 
        private HttpResponse<InputStream> rawResponse;
 
        private Optional<? extends PaymentServiceDefinition> paymentServiceDefinition = Optional.empty();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }

        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }

        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }

        /**
         * Successful Response
         */
        public Builder paymentServiceDefinition(PaymentServiceDefinition paymentServiceDefinition) {
            Utils.checkNotNull(paymentServiceDefinition, "paymentServiceDefinition");
            this.paymentServiceDefinition = Optional.ofNullable(paymentServiceDefinition);
            return this;
        }

        /**
         * Successful Response
         */
        public Builder paymentServiceDefinition(Optional<? extends PaymentServiceDefinition> paymentServiceDefinition) {
            Utils.checkNotNull(paymentServiceDefinition, "paymentServiceDefinition");
            this.paymentServiceDefinition = paymentServiceDefinition;
            return this;
        }
        
        public GetPaymentServiceDefinitionResponse build() {
            return new GetPaymentServiceDefinitionResponse(
                contentType,
                statusCode,
                rawResponse,
                paymentServiceDefinition);
        }
    }
}
