/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gr4vy.sdk.models.operations;

import com.fasterxml.jackson.core.type.TypeReference;
import com.gr4vy.sdk.utils.LazySingletonValue;
import com.gr4vy.sdk.utils.Utils;
import java.lang.Exception;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

public class CreatePaymentServiceDefinitionSessionRequestBuilder {

    private String paymentServiceDefinitionId;
    private Optional<String> applicationName = Utils.readDefaultOrConstValue(
                            "applicationName",
                            "\"core-api\"",
                            new TypeReference<Optional<String>>() {});
    private Map<String, Object> requestBody = new HashMap<>();
    private final SDKMethodInterfaces.MethodCallCreatePaymentServiceDefinitionSession sdk;

    public CreatePaymentServiceDefinitionSessionRequestBuilder(SDKMethodInterfaces.MethodCallCreatePaymentServiceDefinitionSession sdk) {
        this.sdk = sdk;
    }

    public CreatePaymentServiceDefinitionSessionRequestBuilder paymentServiceDefinitionId(String paymentServiceDefinitionId) {
        Utils.checkNotNull(paymentServiceDefinitionId, "paymentServiceDefinitionId");
        this.paymentServiceDefinitionId = paymentServiceDefinitionId;
        return this;
    }
                
    public CreatePaymentServiceDefinitionSessionRequestBuilder applicationName(String applicationName) {
        Utils.checkNotNull(applicationName, "applicationName");
        this.applicationName = Optional.of(applicationName);
        return this;
    }

    public CreatePaymentServiceDefinitionSessionRequestBuilder applicationName(Optional<String> applicationName) {
        Utils.checkNotNull(applicationName, "applicationName");
        this.applicationName = applicationName;
        return this;
    }

    public CreatePaymentServiceDefinitionSessionRequestBuilder requestBody(Map<String, Object> requestBody) {
        Utils.checkNotNull(requestBody, "requestBody");
        this.requestBody = requestBody;
        return this;
    }

    public CreatePaymentServiceDefinitionSessionResponse call() throws Exception {
        if (applicationName == null) {
            applicationName = _SINGLETON_VALUE_ApplicationName.value();
        }
        return sdk.session(
            paymentServiceDefinitionId,
            applicationName,
            requestBody);
    }

    private static final LazySingletonValue<Optional<String>> _SINGLETON_VALUE_ApplicationName =
            new LazySingletonValue<>(
                    "applicationName",
                    "\"core-api\"",
                    new TypeReference<Optional<String>>() {});
}
