/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gr4vy.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.gr4vy.sdk.models.components.ClickToPaySessionRequest;
import com.gr4vy.sdk.utils.LazySingletonValue;
import com.gr4vy.sdk.utils.SpeakeasyMetadata;
import com.gr4vy.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;

public class CreateClickToPayDigitalWalletSessionRequest {

    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=application_name")
    private Optional<String> applicationName;

    @SpeakeasyMetadata("request:mediaType=application/json")
    private ClickToPaySessionRequest clickToPaySessionRequest;

    @JsonCreator
    public CreateClickToPayDigitalWalletSessionRequest(
            Optional<String> applicationName,
            ClickToPaySessionRequest clickToPaySessionRequest) {
        Utils.checkNotNull(applicationName, "applicationName");
        Utils.checkNotNull(clickToPaySessionRequest, "clickToPaySessionRequest");
        this.applicationName = applicationName;
        this.clickToPaySessionRequest = clickToPaySessionRequest;
    }
    
    public CreateClickToPayDigitalWalletSessionRequest(
            ClickToPaySessionRequest clickToPaySessionRequest) {
        this(Optional.empty(), clickToPaySessionRequest);
    }

    @JsonIgnore
    public Optional<String> applicationName() {
        return applicationName;
    }

    @JsonIgnore
    public ClickToPaySessionRequest clickToPaySessionRequest() {
        return clickToPaySessionRequest;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public CreateClickToPayDigitalWalletSessionRequest withApplicationName(String applicationName) {
        Utils.checkNotNull(applicationName, "applicationName");
        this.applicationName = Optional.ofNullable(applicationName);
        return this;
    }

    public CreateClickToPayDigitalWalletSessionRequest withApplicationName(Optional<String> applicationName) {
        Utils.checkNotNull(applicationName, "applicationName");
        this.applicationName = applicationName;
        return this;
    }

    public CreateClickToPayDigitalWalletSessionRequest withClickToPaySessionRequest(ClickToPaySessionRequest clickToPaySessionRequest) {
        Utils.checkNotNull(clickToPaySessionRequest, "clickToPaySessionRequest");
        this.clickToPaySessionRequest = clickToPaySessionRequest;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreateClickToPayDigitalWalletSessionRequest other = (CreateClickToPayDigitalWalletSessionRequest) o;
        return 
            Objects.deepEquals(this.applicationName, other.applicationName) &&
            Objects.deepEquals(this.clickToPaySessionRequest, other.clickToPaySessionRequest);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            applicationName,
            clickToPaySessionRequest);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreateClickToPayDigitalWalletSessionRequest.class,
                "applicationName", applicationName,
                "clickToPaySessionRequest", clickToPaySessionRequest);
    }
    
    public final static class Builder {
 
        private Optional<String> applicationName;
 
        private ClickToPaySessionRequest clickToPaySessionRequest;
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder applicationName(String applicationName) {
            Utils.checkNotNull(applicationName, "applicationName");
            this.applicationName = Optional.ofNullable(applicationName);
            return this;
        }

        public Builder applicationName(Optional<String> applicationName) {
            Utils.checkNotNull(applicationName, "applicationName");
            this.applicationName = applicationName;
            return this;
        }

        public Builder clickToPaySessionRequest(ClickToPaySessionRequest clickToPaySessionRequest) {
            Utils.checkNotNull(clickToPaySessionRequest, "clickToPaySessionRequest");
            this.clickToPaySessionRequest = clickToPaySessionRequest;
            return this;
        }
        
        public CreateClickToPayDigitalWalletSessionRequest build() {
            if (applicationName == null) {
                applicationName = _SINGLETON_VALUE_ApplicationName.value();
            }
            return new CreateClickToPayDigitalWalletSessionRequest(
                applicationName,
                clickToPaySessionRequest);
        }

        private static final LazySingletonValue<Optional<String>> _SINGLETON_VALUE_ApplicationName =
                new LazySingletonValue<>(
                        "application_name",
                        "\"core-api\"",
                        new TypeReference<Optional<String>>() {});
    }
}
