/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gr4vy.sdk.models.operations;

import static com.gr4vy.sdk.operations.Operations.RequestOperation;

import com.gr4vy.sdk.SDKConfiguration;
import com.gr4vy.sdk.operations.DeleteGiftCard;
import com.gr4vy.sdk.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import org.openapitools.jackson.nullable.JsonNullable;

public class DeleteGiftCardRequestBuilder {

    private String giftCardId;
    private JsonNullable<String> merchantAccountId = JsonNullable.undefined();
    private final SDKConfiguration sdkConfiguration;

    public DeleteGiftCardRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public DeleteGiftCardRequestBuilder giftCardId(String giftCardId) {
        Utils.checkNotNull(giftCardId, "giftCardId");
        this.giftCardId = giftCardId;
        return this;
    }

    public DeleteGiftCardRequestBuilder merchantAccountId(String merchantAccountId) {
        Utils.checkNotNull(merchantAccountId, "merchantAccountId");
        this.merchantAccountId = JsonNullable.of(merchantAccountId);
        return this;
    }

    public DeleteGiftCardRequestBuilder merchantAccountId(JsonNullable<String> merchantAccountId) {
        Utils.checkNotNull(merchantAccountId, "merchantAccountId");
        this.merchantAccountId = merchantAccountId;
        return this;
    }


    private DeleteGiftCardRequest buildRequest() {

        DeleteGiftCardRequest request = new DeleteGiftCardRequest(giftCardId,
            merchantAccountId);

        return request;
    }

    public DeleteGiftCardResponse call() throws Exception {
        
        RequestOperation<DeleteGiftCardRequest, DeleteGiftCardResponse> operation
              = new DeleteGiftCard.Sync(sdkConfiguration);
        DeleteGiftCardRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
