/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gr4vy.sdk.models.operations;

import static com.gr4vy.sdk.operations.Operations.RequestOperation;

import com.gr4vy.sdk.SDKConfiguration;
import com.gr4vy.sdk.operations.DeletePaymentService;
import com.gr4vy.sdk.utils.Headers;
import com.gr4vy.sdk.utils.Utils;
import java.lang.String;
import org.openapitools.jackson.nullable.JsonNullable;

public class DeletePaymentServiceRequestBuilder {

    private String paymentServiceId;
    private JsonNullable<String> merchantAccountId = JsonNullable.undefined();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public DeletePaymentServiceRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public DeletePaymentServiceRequestBuilder paymentServiceId(String paymentServiceId) {
        Utils.checkNotNull(paymentServiceId, "paymentServiceId");
        this.paymentServiceId = paymentServiceId;
        return this;
    }

    public DeletePaymentServiceRequestBuilder merchantAccountId(String merchantAccountId) {
        Utils.checkNotNull(merchantAccountId, "merchantAccountId");
        this.merchantAccountId = JsonNullable.of(merchantAccountId);
        return this;
    }

    public DeletePaymentServiceRequestBuilder merchantAccountId(JsonNullable<String> merchantAccountId) {
        Utils.checkNotNull(merchantAccountId, "merchantAccountId");
        this.merchantAccountId = merchantAccountId;
        return this;
    }


    private DeletePaymentServiceRequest buildRequest() {

        DeletePaymentServiceRequest request = new DeletePaymentServiceRequest(paymentServiceId,
            merchantAccountId);

        return request;
    }

    public DeletePaymentServiceResponse call() {
        
        RequestOperation<DeletePaymentServiceRequest, DeletePaymentServiceResponse> operation
              = new DeletePaymentService.Sync(sdkConfiguration, _headers);
        DeletePaymentServiceRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
