/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gr4vy.sdk.models.operations;

import com.gr4vy.sdk.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import org.openapitools.jackson.nullable.JsonNullable;

public class DeleteGiftCardRequestBuilder {

    private String giftCardId;
    private JsonNullable<String> merchantAccountId = JsonNullable.undefined();
    private final SDKMethodInterfaces.MethodCallDeleteGiftCard sdk;

    public DeleteGiftCardRequestBuilder(SDKMethodInterfaces.MethodCallDeleteGiftCard sdk) {
        this.sdk = sdk;
    }

    public DeleteGiftCardRequestBuilder giftCardId(String giftCardId) {
        Utils.checkNotNull(giftCardId, "giftCardId");
        this.giftCardId = giftCardId;
        return this;
    }

    public DeleteGiftCardRequestBuilder merchantAccountId(String merchantAccountId) {
        Utils.checkNotNull(merchantAccountId, "merchantAccountId");
        this.merchantAccountId = JsonNullable.of(merchantAccountId);
        return this;
    }

    public DeleteGiftCardRequestBuilder merchantAccountId(JsonNullable<String> merchantAccountId) {
        Utils.checkNotNull(merchantAccountId, "merchantAccountId");
        this.merchantAccountId = merchantAccountId;
        return this;
    }

    public DeleteGiftCardResponse call() throws Exception {

        return sdk.delete(
            giftCardId,
            merchantAccountId);
    }
}
