/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gr4vy.sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.gr4vy.sdk.utils.LazySingletonValue;
import com.gr4vy.sdk.utils.SpeakeasyMetadata;
import com.gr4vy.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

public class GetBuyerRequest {

    /**
     * The ID of the buyer to retrieve.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=buyer_id")
    private String buyerId;

    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=application_name")
    private Optional<String> applicationName;

    /**
     * The ID of the merchant account to use for this request.
     */
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-gr4vy-merchant-account-id")
    private JsonNullable<String> merchantAccountId;

    @JsonCreator
    public GetBuyerRequest(
            String buyerId,
            Optional<String> applicationName,
            JsonNullable<String> merchantAccountId) {
        Utils.checkNotNull(buyerId, "buyerId");
        Utils.checkNotNull(applicationName, "applicationName");
        Utils.checkNotNull(merchantAccountId, "merchantAccountId");
        this.buyerId = buyerId;
        this.applicationName = applicationName;
        this.merchantAccountId = merchantAccountId;
    }
    
    public GetBuyerRequest(
            String buyerId) {
        this(buyerId, Optional.empty(), JsonNullable.undefined());
    }

    /**
     * The ID of the buyer to retrieve.
     */
    @JsonIgnore
    public String buyerId() {
        return buyerId;
    }

    @JsonIgnore
    public Optional<String> applicationName() {
        return applicationName;
    }

    /**
     * The ID of the merchant account to use for this request.
     */
    @JsonIgnore
    public JsonNullable<String> merchantAccountId() {
        return merchantAccountId;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    /**
     * The ID of the buyer to retrieve.
     */
    public GetBuyerRequest withBuyerId(String buyerId) {
        Utils.checkNotNull(buyerId, "buyerId");
        this.buyerId = buyerId;
        return this;
    }

    public GetBuyerRequest withApplicationName(String applicationName) {
        Utils.checkNotNull(applicationName, "applicationName");
        this.applicationName = Optional.ofNullable(applicationName);
        return this;
    }

    public GetBuyerRequest withApplicationName(Optional<String> applicationName) {
        Utils.checkNotNull(applicationName, "applicationName");
        this.applicationName = applicationName;
        return this;
    }

    /**
     * The ID of the merchant account to use for this request.
     */
    public GetBuyerRequest withMerchantAccountId(String merchantAccountId) {
        Utils.checkNotNull(merchantAccountId, "merchantAccountId");
        this.merchantAccountId = JsonNullable.of(merchantAccountId);
        return this;
    }

    /**
     * The ID of the merchant account to use for this request.
     */
    public GetBuyerRequest withMerchantAccountId(JsonNullable<String> merchantAccountId) {
        Utils.checkNotNull(merchantAccountId, "merchantAccountId");
        this.merchantAccountId = merchantAccountId;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetBuyerRequest other = (GetBuyerRequest) o;
        return 
            Objects.deepEquals(this.buyerId, other.buyerId) &&
            Objects.deepEquals(this.applicationName, other.applicationName) &&
            Objects.deepEquals(this.merchantAccountId, other.merchantAccountId);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            buyerId,
            applicationName,
            merchantAccountId);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetBuyerRequest.class,
                "buyerId", buyerId,
                "applicationName", applicationName,
                "merchantAccountId", merchantAccountId);
    }
    
    public final static class Builder {
 
        private String buyerId;
 
        private Optional<String> applicationName;
 
        private JsonNullable<String> merchantAccountId = JsonNullable.undefined();
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * The ID of the buyer to retrieve.
         */
        public Builder buyerId(String buyerId) {
            Utils.checkNotNull(buyerId, "buyerId");
            this.buyerId = buyerId;
            return this;
        }

        public Builder applicationName(String applicationName) {
            Utils.checkNotNull(applicationName, "applicationName");
            this.applicationName = Optional.ofNullable(applicationName);
            return this;
        }

        public Builder applicationName(Optional<String> applicationName) {
            Utils.checkNotNull(applicationName, "applicationName");
            this.applicationName = applicationName;
            return this;
        }

        /**
         * The ID of the merchant account to use for this request.
         */
        public Builder merchantAccountId(String merchantAccountId) {
            Utils.checkNotNull(merchantAccountId, "merchantAccountId");
            this.merchantAccountId = JsonNullable.of(merchantAccountId);
            return this;
        }

        /**
         * The ID of the merchant account to use for this request.
         */
        public Builder merchantAccountId(JsonNullable<String> merchantAccountId) {
            Utils.checkNotNull(merchantAccountId, "merchantAccountId");
            this.merchantAccountId = merchantAccountId;
            return this;
        }
        
        public GetBuyerRequest build() {
            if (applicationName == null) {
                applicationName = _SINGLETON_VALUE_ApplicationName.value();
            }
            return new GetBuyerRequest(
                buyerId,
                applicationName,
                merchantAccountId);
        }

        private static final LazySingletonValue<Optional<String>> _SINGLETON_VALUE_ApplicationName =
                new LazySingletonValue<>(
                        "application_name",
                        "\"core-api\"",
                        new TypeReference<Optional<String>>() {});
    }
}
