/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gr4vy.sdk.models.operations;

import static com.gr4vy.sdk.operations.Operations.RequestOperation;

import com.gr4vy.sdk.SDKConfiguration;
import com.gr4vy.sdk.operations.SuspendPaymentMethodNetworkToken;
import com.gr4vy.sdk.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import org.openapitools.jackson.nullable.JsonNullable;

public class SuspendPaymentMethodNetworkTokenRequestBuilder {

    private String paymentMethodId;
    private String networkTokenId;
    private JsonNullable<String> merchantAccountId = JsonNullable.undefined();
    private final SDKConfiguration sdkConfiguration;

    public SuspendPaymentMethodNetworkTokenRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public SuspendPaymentMethodNetworkTokenRequestBuilder paymentMethodId(String paymentMethodId) {
        Utils.checkNotNull(paymentMethodId, "paymentMethodId");
        this.paymentMethodId = paymentMethodId;
        return this;
    }

    public SuspendPaymentMethodNetworkTokenRequestBuilder networkTokenId(String networkTokenId) {
        Utils.checkNotNull(networkTokenId, "networkTokenId");
        this.networkTokenId = networkTokenId;
        return this;
    }

    public SuspendPaymentMethodNetworkTokenRequestBuilder merchantAccountId(String merchantAccountId) {
        Utils.checkNotNull(merchantAccountId, "merchantAccountId");
        this.merchantAccountId = JsonNullable.of(merchantAccountId);
        return this;
    }

    public SuspendPaymentMethodNetworkTokenRequestBuilder merchantAccountId(JsonNullable<String> merchantAccountId) {
        Utils.checkNotNull(merchantAccountId, "merchantAccountId");
        this.merchantAccountId = merchantAccountId;
        return this;
    }


    private SuspendPaymentMethodNetworkTokenRequest buildRequest() {

        SuspendPaymentMethodNetworkTokenRequest request = new SuspendPaymentMethodNetworkTokenRequest(paymentMethodId,
            networkTokenId,
            merchantAccountId);

        return request;
    }

    public SuspendPaymentMethodNetworkTokenResponse call() throws Exception {
        
        RequestOperation<SuspendPaymentMethodNetworkTokenRequest, SuspendPaymentMethodNetworkTokenResponse> operation
              = new SuspendPaymentMethodNetworkToken.Sync(sdkConfiguration);
        SuspendPaymentMethodNetworkTokenRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
