/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gr4vy.sdk.models.operations;

import static com.gr4vy.sdk.operations.Operations.RequestOperation;

import com.gr4vy.sdk.SDKConfiguration;
import com.gr4vy.sdk.models.components.DigitalWalletDomain;
import com.gr4vy.sdk.operations.UnregisterDigitalWalletDomainOperation;
import com.gr4vy.sdk.utils.Utils;
import java.lang.Exception;
import java.lang.String;
import org.openapitools.jackson.nullable.JsonNullable;

public class UnregisterDigitalWalletDomainRequestBuilder {

    private String digitalWalletId;
    private JsonNullable<String> merchantAccountId = JsonNullable.undefined();
    private DigitalWalletDomain digitalWalletDomain;
    private final SDKConfiguration sdkConfiguration;

    public UnregisterDigitalWalletDomainRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public UnregisterDigitalWalletDomainRequestBuilder digitalWalletId(String digitalWalletId) {
        Utils.checkNotNull(digitalWalletId, "digitalWalletId");
        this.digitalWalletId = digitalWalletId;
        return this;
    }

    public UnregisterDigitalWalletDomainRequestBuilder merchantAccountId(String merchantAccountId) {
        Utils.checkNotNull(merchantAccountId, "merchantAccountId");
        this.merchantAccountId = JsonNullable.of(merchantAccountId);
        return this;
    }

    public UnregisterDigitalWalletDomainRequestBuilder merchantAccountId(JsonNullable<String> merchantAccountId) {
        Utils.checkNotNull(merchantAccountId, "merchantAccountId");
        this.merchantAccountId = merchantAccountId;
        return this;
    }

    public UnregisterDigitalWalletDomainRequestBuilder digitalWalletDomain(DigitalWalletDomain digitalWalletDomain) {
        Utils.checkNotNull(digitalWalletDomain, "digitalWalletDomain");
        this.digitalWalletDomain = digitalWalletDomain;
        return this;
    }


    private UnregisterDigitalWalletDomainRequest buildRequest() {

        UnregisterDigitalWalletDomainRequest request = new UnregisterDigitalWalletDomainRequest(digitalWalletId,
            merchantAccountId,
            digitalWalletDomain);

        return request;
    }

    public UnregisterDigitalWalletDomainResponse call() throws Exception {
        
        RequestOperation<UnregisterDigitalWalletDomainRequest, UnregisterDigitalWalletDomainResponse> operation
              = new UnregisterDigitalWalletDomainOperation( sdkConfiguration);
        UnregisterDigitalWalletDomainRequest request = buildRequest();

        return operation.handleResponse(operation.doRequest(request));
    }
}
