workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Gr4vy:
        inputs:
            - location: https://gr4vy.github.io/gr4vy-openapi/core/openapi.json
        registry:
            location: registry.speakeasyapi.dev/gr4vy/gr4vy/openapi
targets:
    java:
        target: java
        source: Gr4vy
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/gr4vy/gr4vy/openapi-java-code-samples
            labelOverride:
                fixedValue: Java
            blocking: false
