/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gr4vy.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.gr4vy.sdk.utils.LazySingletonValue;
import com.gr4vy.sdk.utils.Utils;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;


public class ApiCommonSchemasMerchantAccount {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private Optional<String> type;


    @JsonProperty("id")
    private String id;


    @JsonProperty("display_name")
    private String displayName;


    @JsonProperty("created_at")
    private OffsetDateTime createdAt;


    @JsonProperty("updated_at")
    private OffsetDateTime updatedAt;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("over_capture_amount")
    private JsonNullable<Long> overCaptureAmount;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("over_capture_percentage")
    private JsonNullable<Long> overCapturePercentage;

    @JsonCreator
    public ApiCommonSchemasMerchantAccount(
            @JsonProperty("id") String id,
            @JsonProperty("display_name") String displayName,
            @JsonProperty("created_at") OffsetDateTime createdAt,
            @JsonProperty("updated_at") OffsetDateTime updatedAt,
            @JsonProperty("over_capture_amount") JsonNullable<Long> overCaptureAmount,
            @JsonProperty("over_capture_percentage") JsonNullable<Long> overCapturePercentage) {
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(displayName, "displayName");
        Utils.checkNotNull(createdAt, "createdAt");
        Utils.checkNotNull(updatedAt, "updatedAt");
        Utils.checkNotNull(overCaptureAmount, "overCaptureAmount");
        Utils.checkNotNull(overCapturePercentage, "overCapturePercentage");
        this.type = Builder._SINGLETON_VALUE_Type.value();
        this.id = id;
        this.displayName = displayName;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.overCaptureAmount = overCaptureAmount;
        this.overCapturePercentage = overCapturePercentage;
    }
    
    public ApiCommonSchemasMerchantAccount(
            String id,
            String displayName,
            OffsetDateTime createdAt,
            OffsetDateTime updatedAt) {
        this(id, displayName, createdAt,
            updatedAt, JsonNullable.undefined(), JsonNullable.undefined());
    }

    @JsonIgnore
    public Optional<String> type() {
        return type;
    }

    @JsonIgnore
    public String id() {
        return id;
    }

    @JsonIgnore
    public String displayName() {
        return displayName;
    }

    @JsonIgnore
    public OffsetDateTime createdAt() {
        return createdAt;
    }

    @JsonIgnore
    public OffsetDateTime updatedAt() {
        return updatedAt;
    }

    @JsonIgnore
    public JsonNullable<Long> overCaptureAmount() {
        return overCaptureAmount;
    }

    @JsonIgnore
    public JsonNullable<Long> overCapturePercentage() {
        return overCapturePercentage;
    }

    public static Builder builder() {
        return new Builder();
    }


    public ApiCommonSchemasMerchantAccount withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public ApiCommonSchemasMerchantAccount withDisplayName(String displayName) {
        Utils.checkNotNull(displayName, "displayName");
        this.displayName = displayName;
        return this;
    }

    public ApiCommonSchemasMerchantAccount withCreatedAt(OffsetDateTime createdAt) {
        Utils.checkNotNull(createdAt, "createdAt");
        this.createdAt = createdAt;
        return this;
    }

    public ApiCommonSchemasMerchantAccount withUpdatedAt(OffsetDateTime updatedAt) {
        Utils.checkNotNull(updatedAt, "updatedAt");
        this.updatedAt = updatedAt;
        return this;
    }

    public ApiCommonSchemasMerchantAccount withOverCaptureAmount(long overCaptureAmount) {
        Utils.checkNotNull(overCaptureAmount, "overCaptureAmount");
        this.overCaptureAmount = JsonNullable.of(overCaptureAmount);
        return this;
    }

    public ApiCommonSchemasMerchantAccount withOverCaptureAmount(JsonNullable<Long> overCaptureAmount) {
        Utils.checkNotNull(overCaptureAmount, "overCaptureAmount");
        this.overCaptureAmount = overCaptureAmount;
        return this;
    }

    public ApiCommonSchemasMerchantAccount withOverCapturePercentage(long overCapturePercentage) {
        Utils.checkNotNull(overCapturePercentage, "overCapturePercentage");
        this.overCapturePercentage = JsonNullable.of(overCapturePercentage);
        return this;
    }

    public ApiCommonSchemasMerchantAccount withOverCapturePercentage(JsonNullable<Long> overCapturePercentage) {
        Utils.checkNotNull(overCapturePercentage, "overCapturePercentage");
        this.overCapturePercentage = overCapturePercentage;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ApiCommonSchemasMerchantAccount other = (ApiCommonSchemasMerchantAccount) o;
        return 
            Utils.enhancedDeepEquals(this.type, other.type) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.displayName, other.displayName) &&
            Utils.enhancedDeepEquals(this.createdAt, other.createdAt) &&
            Utils.enhancedDeepEquals(this.updatedAt, other.updatedAt) &&
            Utils.enhancedDeepEquals(this.overCaptureAmount, other.overCaptureAmount) &&
            Utils.enhancedDeepEquals(this.overCapturePercentage, other.overCapturePercentage);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            type, id, displayName,
            createdAt, updatedAt, overCaptureAmount,
            overCapturePercentage);
    }
    
    @Override
    public String toString() {
        return Utils.toString(ApiCommonSchemasMerchantAccount.class,
                "type", type,
                "id", id,
                "displayName", displayName,
                "createdAt", createdAt,
                "updatedAt", updatedAt,
                "overCaptureAmount", overCaptureAmount,
                "overCapturePercentage", overCapturePercentage);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String id;

        private String displayName;

        private OffsetDateTime createdAt;

        private OffsetDateTime updatedAt;

        private JsonNullable<Long> overCaptureAmount = JsonNullable.undefined();

        private JsonNullable<Long> overCapturePercentage = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }


        public Builder displayName(String displayName) {
            Utils.checkNotNull(displayName, "displayName");
            this.displayName = displayName;
            return this;
        }


        public Builder createdAt(OffsetDateTime createdAt) {
            Utils.checkNotNull(createdAt, "createdAt");
            this.createdAt = createdAt;
            return this;
        }


        public Builder updatedAt(OffsetDateTime updatedAt) {
            Utils.checkNotNull(updatedAt, "updatedAt");
            this.updatedAt = updatedAt;
            return this;
        }


        public Builder overCaptureAmount(long overCaptureAmount) {
            Utils.checkNotNull(overCaptureAmount, "overCaptureAmount");
            this.overCaptureAmount = JsonNullable.of(overCaptureAmount);
            return this;
        }

        public Builder overCaptureAmount(JsonNullable<Long> overCaptureAmount) {
            Utils.checkNotNull(overCaptureAmount, "overCaptureAmount");
            this.overCaptureAmount = overCaptureAmount;
            return this;
        }


        public Builder overCapturePercentage(long overCapturePercentage) {
            Utils.checkNotNull(overCapturePercentage, "overCapturePercentage");
            this.overCapturePercentage = JsonNullable.of(overCapturePercentage);
            return this;
        }

        public Builder overCapturePercentage(JsonNullable<Long> overCapturePercentage) {
            Utils.checkNotNull(overCapturePercentage, "overCapturePercentage");
            this.overCapturePercentage = overCapturePercentage;
            return this;
        }

        public ApiCommonSchemasMerchantAccount build() {

            return new ApiCommonSchemasMerchantAccount(
                id, displayName, createdAt,
                updatedAt, overCaptureAmount, overCapturePercentage);
        }


        private static final LazySingletonValue<Optional<String>> _SINGLETON_VALUE_Type =
                new LazySingletonValue<>(
                        "type",
                        "\"merchant-account\"",
                        new TypeReference<Optional<String>>() {});
    }
}
