/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gr4vy.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gr4vy.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * PaymentMethodUpdate
 * 
 * <p>Request body for updating a stored payment method.
 */
public class PaymentMethodUpdate {
    /**
     * The new expiration date for the payment method.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("expiration_date")
    private JsonNullable<String> expirationDate;

    /**
     * A scheme transaction identifier to associate with this payment method. Explicitly setting this field
     * to `null` will also clear `scheme_transaction_id_scheme` as a side-effect. When setting a new value
     * and `scheme_transaction_id_scheme` is both omitted from the payload and previously
     * unset,`scheme_transaction_id_scheme` will be populated from the payment method's existing `scheme`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("scheme_transaction_id")
    private JsonNullable<String> schemeTransactionId;

    /**
     * The scheme associated with `scheme_transaction_id`. Only applies to card payments. When setting a
     * new value for `scheme_transaction_id`, if `scheme_transaction_id_scheme`is both omitted from the
     * payload and previously unset, `scheme_transaction_id_scheme` will be populated from the payment
     * method's existing `scheme`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("scheme_transaction_id_scheme")
    private JsonNullable<? extends CardScheme> schemeTransactionIdScheme;

    @JsonCreator
    public PaymentMethodUpdate(
            @JsonProperty("expiration_date") JsonNullable<String> expirationDate,
            @JsonProperty("scheme_transaction_id") JsonNullable<String> schemeTransactionId,
            @JsonProperty("scheme_transaction_id_scheme") JsonNullable<? extends CardScheme> schemeTransactionIdScheme) {
        Utils.checkNotNull(expirationDate, "expirationDate");
        Utils.checkNotNull(schemeTransactionId, "schemeTransactionId");
        Utils.checkNotNull(schemeTransactionIdScheme, "schemeTransactionIdScheme");
        this.expirationDate = expirationDate;
        this.schemeTransactionId = schemeTransactionId;
        this.schemeTransactionIdScheme = schemeTransactionIdScheme;
    }
    
    public PaymentMethodUpdate() {
        this(JsonNullable.undefined(), JsonNullable.undefined(), JsonNullable.undefined());
    }

    /**
     * The new expiration date for the payment method.
     */
    @JsonIgnore
    public JsonNullable<String> expirationDate() {
        return expirationDate;
    }

    /**
     * A scheme transaction identifier to associate with this payment method. Explicitly setting this field
     * to `null` will also clear `scheme_transaction_id_scheme` as a side-effect. When setting a new value
     * and `scheme_transaction_id_scheme` is both omitted from the payload and previously
     * unset,`scheme_transaction_id_scheme` will be populated from the payment method's existing `scheme`.
     */
    @JsonIgnore
    public JsonNullable<String> schemeTransactionId() {
        return schemeTransactionId;
    }

    /**
     * The scheme associated with `scheme_transaction_id`. Only applies to card payments. When setting a
     * new value for `scheme_transaction_id`, if `scheme_transaction_id_scheme`is both omitted from the
     * payload and previously unset, `scheme_transaction_id_scheme` will be populated from the payment
     * method's existing `scheme`.
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public JsonNullable<CardScheme> schemeTransactionIdScheme() {
        return (JsonNullable<CardScheme>) schemeTransactionIdScheme;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The new expiration date for the payment method.
     */
    public PaymentMethodUpdate withExpirationDate(String expirationDate) {
        Utils.checkNotNull(expirationDate, "expirationDate");
        this.expirationDate = JsonNullable.of(expirationDate);
        return this;
    }

    /**
     * The new expiration date for the payment method.
     */
    public PaymentMethodUpdate withExpirationDate(JsonNullable<String> expirationDate) {
        Utils.checkNotNull(expirationDate, "expirationDate");
        this.expirationDate = expirationDate;
        return this;
    }

    /**
     * A scheme transaction identifier to associate with this payment method. Explicitly setting this field
     * to `null` will also clear `scheme_transaction_id_scheme` as a side-effect. When setting a new value
     * and `scheme_transaction_id_scheme` is both omitted from the payload and previously
     * unset,`scheme_transaction_id_scheme` will be populated from the payment method's existing `scheme`.
     */
    public PaymentMethodUpdate withSchemeTransactionId(String schemeTransactionId) {
        Utils.checkNotNull(schemeTransactionId, "schemeTransactionId");
        this.schemeTransactionId = JsonNullable.of(schemeTransactionId);
        return this;
    }

    /**
     * A scheme transaction identifier to associate with this payment method. Explicitly setting this field
     * to `null` will also clear `scheme_transaction_id_scheme` as a side-effect. When setting a new value
     * and `scheme_transaction_id_scheme` is both omitted from the payload and previously
     * unset,`scheme_transaction_id_scheme` will be populated from the payment method's existing `scheme`.
     */
    public PaymentMethodUpdate withSchemeTransactionId(JsonNullable<String> schemeTransactionId) {
        Utils.checkNotNull(schemeTransactionId, "schemeTransactionId");
        this.schemeTransactionId = schemeTransactionId;
        return this;
    }

    /**
     * The scheme associated with `scheme_transaction_id`. Only applies to card payments. When setting a
     * new value for `scheme_transaction_id`, if `scheme_transaction_id_scheme`is both omitted from the
     * payload and previously unset, `scheme_transaction_id_scheme` will be populated from the payment
     * method's existing `scheme`.
     */
    public PaymentMethodUpdate withSchemeTransactionIdScheme(CardScheme schemeTransactionIdScheme) {
        Utils.checkNotNull(schemeTransactionIdScheme, "schemeTransactionIdScheme");
        this.schemeTransactionIdScheme = JsonNullable.of(schemeTransactionIdScheme);
        return this;
    }

    /**
     * The scheme associated with `scheme_transaction_id`. Only applies to card payments. When setting a
     * new value for `scheme_transaction_id`, if `scheme_transaction_id_scheme`is both omitted from the
     * payload and previously unset, `scheme_transaction_id_scheme` will be populated from the payment
     * method's existing `scheme`.
     */
    public PaymentMethodUpdate withSchemeTransactionIdScheme(JsonNullable<? extends CardScheme> schemeTransactionIdScheme) {
        Utils.checkNotNull(schemeTransactionIdScheme, "schemeTransactionIdScheme");
        this.schemeTransactionIdScheme = schemeTransactionIdScheme;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PaymentMethodUpdate other = (PaymentMethodUpdate) o;
        return 
            Utils.enhancedDeepEquals(this.expirationDate, other.expirationDate) &&
            Utils.enhancedDeepEquals(this.schemeTransactionId, other.schemeTransactionId) &&
            Utils.enhancedDeepEquals(this.schemeTransactionIdScheme, other.schemeTransactionIdScheme);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            expirationDate, schemeTransactionId, schemeTransactionIdScheme);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PaymentMethodUpdate.class,
                "expirationDate", expirationDate,
                "schemeTransactionId", schemeTransactionId,
                "schemeTransactionIdScheme", schemeTransactionIdScheme);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private JsonNullable<String> expirationDate = JsonNullable.undefined();

        private JsonNullable<String> schemeTransactionId = JsonNullable.undefined();

        private JsonNullable<? extends CardScheme> schemeTransactionIdScheme = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The new expiration date for the payment method.
         */
        public Builder expirationDate(String expirationDate) {
            Utils.checkNotNull(expirationDate, "expirationDate");
            this.expirationDate = JsonNullable.of(expirationDate);
            return this;
        }

        /**
         * The new expiration date for the payment method.
         */
        public Builder expirationDate(JsonNullable<String> expirationDate) {
            Utils.checkNotNull(expirationDate, "expirationDate");
            this.expirationDate = expirationDate;
            return this;
        }


        /**
         * A scheme transaction identifier to associate with this payment method. Explicitly setting this field
         * to `null` will also clear `scheme_transaction_id_scheme` as a side-effect. When setting a new value
         * and `scheme_transaction_id_scheme` is both omitted from the payload and previously
         * unset,`scheme_transaction_id_scheme` will be populated from the payment method's existing `scheme`.
         */
        public Builder schemeTransactionId(String schemeTransactionId) {
            Utils.checkNotNull(schemeTransactionId, "schemeTransactionId");
            this.schemeTransactionId = JsonNullable.of(schemeTransactionId);
            return this;
        }

        /**
         * A scheme transaction identifier to associate with this payment method. Explicitly setting this field
         * to `null` will also clear `scheme_transaction_id_scheme` as a side-effect. When setting a new value
         * and `scheme_transaction_id_scheme` is both omitted from the payload and previously
         * unset,`scheme_transaction_id_scheme` will be populated from the payment method's existing `scheme`.
         */
        public Builder schemeTransactionId(JsonNullable<String> schemeTransactionId) {
            Utils.checkNotNull(schemeTransactionId, "schemeTransactionId");
            this.schemeTransactionId = schemeTransactionId;
            return this;
        }


        /**
         * The scheme associated with `scheme_transaction_id`. Only applies to card payments. When setting a
         * new value for `scheme_transaction_id`, if `scheme_transaction_id_scheme`is both omitted from the
         * payload and previously unset, `scheme_transaction_id_scheme` will be populated from the payment
         * method's existing `scheme`.
         */
        public Builder schemeTransactionIdScheme(CardScheme schemeTransactionIdScheme) {
            Utils.checkNotNull(schemeTransactionIdScheme, "schemeTransactionIdScheme");
            this.schemeTransactionIdScheme = JsonNullable.of(schemeTransactionIdScheme);
            return this;
        }

        /**
         * The scheme associated with `scheme_transaction_id`. Only applies to card payments. When setting a
         * new value for `scheme_transaction_id`, if `scheme_transaction_id_scheme`is both omitted from the
         * payload and previously unset, `scheme_transaction_id_scheme` will be populated from the payment
         * method's existing `scheme`.
         */
        public Builder schemeTransactionIdScheme(JsonNullable<? extends CardScheme> schemeTransactionIdScheme) {
            Utils.checkNotNull(schemeTransactionIdScheme, "schemeTransactionIdScheme");
            this.schemeTransactionIdScheme = schemeTransactionIdScheme;
            return this;
        }

        public PaymentMethodUpdate build() {

            return new PaymentMethodUpdate(
                expirationDate, schemeTransactionId, schemeTransactionIdScheme);
        }

    }
}
