/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gr4vy.sdk.models.components;

import com.fasterxml.jackson.core.JacksonException;
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import java.io.IOException;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * <p>Wrapper class for an "open" enum. "Open" enums are those that are expected
 * to evolve (particularly with the addition of enum members over time). If an
 * open enum is used then the appearance of unexpected enum values (say in a 
 * response from an updated an API) will not bring about a runtime error thus 
 * ensuring that non-updated client versions can continue to work without error.
 *
 * <p>Note that instances are immutable and are singletons (an internal thread-safe
 * cache is maintained to ensure that). As a consequence instances created with the 
 * same value will satisfy reference equality (via {@code ==}).
 * 
 * <p>This class is intended to emulate an enum (in terms of common usage and with 
 * reference equality) but with the ability to carry unknown values. Unfortunately
 * Java does not permit the use of an instance in a switch expression but you can 
 * use the {@code asEnum()} method (after dealing with the `Optional` appropriately).
 *
 */
@JsonDeserialize(using = PaypalShippingOptionsItemType._Deserializer.class)
@JsonSerialize(using = PaypalShippingOptionsItemType._Serializer.class)
public class PaypalShippingOptionsItemType {

    public static final PaypalShippingOptionsItemType SHIPPING = new PaypalShippingOptionsItemType("SHIPPING");
    public static final PaypalShippingOptionsItemType PICKUP = new PaypalShippingOptionsItemType("PICKUP");
    public static final PaypalShippingOptionsItemType PICKUP_IN_STORE = new PaypalShippingOptionsItemType("PICKUP_IN_STORE");
    public static final PaypalShippingOptionsItemType PICKUP_FROM_PERSON = new PaypalShippingOptionsItemType("PICKUP_FROM_PERSON");

    // This map will grow whenever a Color gets created with a new
    // unrecognized value (a potential memory leak if the user is not
    // careful). Keep this field lower case to avoid clashing with
    // generated member names which will always be upper cased (Java
    // convention)
    private static final Map<String, PaypalShippingOptionsItemType> values = createValuesMap();
    private static final Map<String, PaypalShippingOptionsItemTypeEnum> enums = createEnumsMap();

    private final String value;

    private PaypalShippingOptionsItemType(String value) {
        this.value = value;
    }

    /**
     * Returns a PaypalShippingOptionsItemType with the given value. For a specific value the 
     * returned object will always be a singleton so reference equality 
     * is satisfied when the values are the same.
     * 
     * @param value value to be wrapped as PaypalShippingOptionsItemType
     */ 
    public static PaypalShippingOptionsItemType of(String value) {
        synchronized (PaypalShippingOptionsItemType.class) {
            return values.computeIfAbsent(value, v -> new PaypalShippingOptionsItemType(v));
        }
    }

    public String value() {
        return value;
    }

    public Optional<PaypalShippingOptionsItemTypeEnum> asEnum() {
        return Optional.ofNullable(enums.getOrDefault(value, null));
    }

    public boolean isKnown() {
        return asEnum().isPresent();
    }

    @Override
    public int hashCode() {
        return Objects.hash(value);
    }

    @Override
    public boolean equals(java.lang.Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        PaypalShippingOptionsItemType other = (PaypalShippingOptionsItemType) obj;
        return Objects.equals(value, other.value);
    }

    @Override
    public String toString() {
        return "PaypalShippingOptionsItemType [value=" + value + "]";
    }

    // return an array just like an enum
    public static PaypalShippingOptionsItemType[] values() {
        synchronized (PaypalShippingOptionsItemType.class) {
            return values.values().toArray(new PaypalShippingOptionsItemType[] {});
        }
    }

    private static final Map<String, PaypalShippingOptionsItemType> createValuesMap() {
        Map<String, PaypalShippingOptionsItemType> map = new LinkedHashMap<>();
        map.put("SHIPPING", SHIPPING);
        map.put("PICKUP", PICKUP);
        map.put("PICKUP_IN_STORE", PICKUP_IN_STORE);
        map.put("PICKUP_FROM_PERSON", PICKUP_FROM_PERSON);
        return map;
    }

    private static final Map<String, PaypalShippingOptionsItemTypeEnum> createEnumsMap() {
        Map<String, PaypalShippingOptionsItemTypeEnum> map = new HashMap<>();
        map.put("SHIPPING", PaypalShippingOptionsItemTypeEnum.SHIPPING);
        map.put("PICKUP", PaypalShippingOptionsItemTypeEnum.PICKUP);
        map.put("PICKUP_IN_STORE", PaypalShippingOptionsItemTypeEnum.PICKUP_IN_STORE);
        map.put("PICKUP_FROM_PERSON", PaypalShippingOptionsItemTypeEnum.PICKUP_FROM_PERSON);
        return map;
    }
    
    @SuppressWarnings("serial")
    public static final class _Serializer extends StdSerializer<PaypalShippingOptionsItemType> {

        protected _Serializer() {
            super(PaypalShippingOptionsItemType.class);
        }

        @Override
        public void serialize(PaypalShippingOptionsItemType value, JsonGenerator g, SerializerProvider provider)
                throws IOException, JsonProcessingException {
            g.writeObject(value.value);
        }
    }

    @SuppressWarnings("serial")
    public static final class _Deserializer extends StdDeserializer<PaypalShippingOptionsItemType> {

        protected _Deserializer() {
            super(PaypalShippingOptionsItemType.class);
        }

        @Override
        public PaypalShippingOptionsItemType deserialize(JsonParser p, DeserializationContext ctxt)
                throws IOException, JacksonException {
            String v = p.readValueAs(new TypeReference<String>() {});
            // use the factory method to ensure we get singletons
            return PaypalShippingOptionsItemType.of(v);
        }
    }
    
    public enum PaypalShippingOptionsItemTypeEnum {

        SHIPPING("SHIPPING"),
        PICKUP("PICKUP"),
        PICKUP_IN_STORE("PICKUP_IN_STORE"),
        PICKUP_FROM_PERSON("PICKUP_FROM_PERSON"),;

        private final String value;

        private PaypalShippingOptionsItemTypeEnum(String value) {
            this.value = value;
        }

        public String value() {
            return value;
        }
    }
}

