/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gr4vy.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.gr4vy.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class PaypalShippingOptionsItemAmount {
    /**
     * The three-character ISO currency code.
     */
    @JsonProperty("currency_code")
    private String currencyCode;

    /**
     * The amount value, which might include a decimal portion.
     */
    @JsonProperty("value")
    private String value;

    @JsonCreator
    public PaypalShippingOptionsItemAmount(
            @JsonProperty("currency_code") String currencyCode,
            @JsonProperty("value") String value) {
        Utils.checkNotNull(currencyCode, "currencyCode");
        Utils.checkNotNull(value, "value");
        this.currencyCode = currencyCode;
        this.value = value;
    }

    /**
     * The three-character ISO currency code.
     */
    @JsonIgnore
    public String currencyCode() {
        return currencyCode;
    }

    /**
     * The amount value, which might include a decimal portion.
     */
    @JsonIgnore
    public String value() {
        return value;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The three-character ISO currency code.
     */
    public PaypalShippingOptionsItemAmount withCurrencyCode(String currencyCode) {
        Utils.checkNotNull(currencyCode, "currencyCode");
        this.currencyCode = currencyCode;
        return this;
    }

    /**
     * The amount value, which might include a decimal portion.
     */
    public PaypalShippingOptionsItemAmount withValue(String value) {
        Utils.checkNotNull(value, "value");
        this.value = value;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PaypalShippingOptionsItemAmount other = (PaypalShippingOptionsItemAmount) o;
        return 
            Utils.enhancedDeepEquals(this.currencyCode, other.currencyCode) &&
            Utils.enhancedDeepEquals(this.value, other.value);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            currencyCode, value);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PaypalShippingOptionsItemAmount.class,
                "currencyCode", currencyCode,
                "value", value);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String currencyCode;

        private String value;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The three-character ISO currency code.
         */
        public Builder currencyCode(String currencyCode) {
            Utils.checkNotNull(currencyCode, "currencyCode");
            this.currencyCode = currencyCode;
            return this;
        }


        /**
         * The amount value, which might include a decimal portion.
         */
        public Builder value(String value) {
            Utils.checkNotNull(value, "value");
            this.value = value;
            return this;
        }

        public PaypalShippingOptionsItemAmount build() {

            return new PaypalShippingOptionsItemAmount(
                currencyCode, value);
        }

    }
}
