/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gr4vy.sdk.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.gr4vy.sdk.utils.LazySingletonValue;
import com.gr4vy.sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Optional;
import org.openapitools.jackson.nullable.JsonNullable;

/**
 * SEPABankPaymentMethodCreate
 * 
 * <p>SEPA Bank Payment Method
 * 
 * <p>Bank Payment Method for SEPA bank accounts.
 */
public class SEPABankPaymentMethodCreate {
    /**
     * Always `bank`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("method")
    private Optional<String> method;


    @JsonProperty("account_holder")
    private BankAccountHolder accountHolder;

    /**
     * The ID of the buyer to attach the method to.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("buyer_id")
    private JsonNullable<String> buyerId;

    /**
     * The merchant reference for this payment method.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("buyer_external_identifier")
    private JsonNullable<String> buyerExternalIdentifier;

    /**
     * The merchant identifier for this payment method.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("external_identifier")
    private JsonNullable<String> externalIdentifier;

    /**
     * Always `sepa`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("scheme")
    private Optional<String> scheme;

    /**
     * The IBAN for this SEPA bank account
     */
    @JsonProperty("account_number")
    private String accountNumber;

    /**
     * The BIC for this SEPA bank account
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("routing_number")
    private JsonNullable<String> routingNumber;

    @JsonCreator
    public SEPABankPaymentMethodCreate(
            @JsonProperty("account_holder") BankAccountHolder accountHolder,
            @JsonProperty("buyer_id") JsonNullable<String> buyerId,
            @JsonProperty("buyer_external_identifier") JsonNullable<String> buyerExternalIdentifier,
            @JsonProperty("external_identifier") JsonNullable<String> externalIdentifier,
            @JsonProperty("account_number") String accountNumber,
            @JsonProperty("routing_number") JsonNullable<String> routingNumber) {
        Utils.checkNotNull(accountHolder, "accountHolder");
        Utils.checkNotNull(buyerId, "buyerId");
        Utils.checkNotNull(buyerExternalIdentifier, "buyerExternalIdentifier");
        Utils.checkNotNull(externalIdentifier, "externalIdentifier");
        Utils.checkNotNull(accountNumber, "accountNumber");
        Utils.checkNotNull(routingNumber, "routingNumber");
        this.method = Builder._SINGLETON_VALUE_Method.value();
        this.accountHolder = accountHolder;
        this.buyerId = buyerId;
        this.buyerExternalIdentifier = buyerExternalIdentifier;
        this.externalIdentifier = externalIdentifier;
        this.scheme = Builder._SINGLETON_VALUE_Scheme.value();
        this.accountNumber = accountNumber;
        this.routingNumber = routingNumber;
    }
    
    public SEPABankPaymentMethodCreate(
            BankAccountHolder accountHolder,
            String accountNumber) {
        this(accountHolder, JsonNullable.undefined(), JsonNullable.undefined(),
            JsonNullable.undefined(), accountNumber, JsonNullable.undefined());
    }

    /**
     * Always `bank`.
     */
    @JsonIgnore
    public Optional<String> method() {
        return method;
    }

    @JsonIgnore
    public BankAccountHolder accountHolder() {
        return accountHolder;
    }

    /**
     * The ID of the buyer to attach the method to.
     */
    @JsonIgnore
    public JsonNullable<String> buyerId() {
        return buyerId;
    }

    /**
     * The merchant reference for this payment method.
     */
    @JsonIgnore
    public JsonNullable<String> buyerExternalIdentifier() {
        return buyerExternalIdentifier;
    }

    /**
     * The merchant identifier for this payment method.
     */
    @JsonIgnore
    public JsonNullable<String> externalIdentifier() {
        return externalIdentifier;
    }

    /**
     * Always `sepa`.
     */
    @JsonIgnore
    public Optional<String> scheme() {
        return scheme;
    }

    /**
     * The IBAN for this SEPA bank account
     */
    @JsonIgnore
    public String accountNumber() {
        return accountNumber;
    }

    /**
     * The BIC for this SEPA bank account
     */
    @JsonIgnore
    public JsonNullable<String> routingNumber() {
        return routingNumber;
    }

    public static Builder builder() {
        return new Builder();
    }


    public SEPABankPaymentMethodCreate withAccountHolder(BankAccountHolder accountHolder) {
        Utils.checkNotNull(accountHolder, "accountHolder");
        this.accountHolder = accountHolder;
        return this;
    }

    /**
     * The ID of the buyer to attach the method to.
     */
    public SEPABankPaymentMethodCreate withBuyerId(String buyerId) {
        Utils.checkNotNull(buyerId, "buyerId");
        this.buyerId = JsonNullable.of(buyerId);
        return this;
    }

    /**
     * The ID of the buyer to attach the method to.
     */
    public SEPABankPaymentMethodCreate withBuyerId(JsonNullable<String> buyerId) {
        Utils.checkNotNull(buyerId, "buyerId");
        this.buyerId = buyerId;
        return this;
    }

    /**
     * The merchant reference for this payment method.
     */
    public SEPABankPaymentMethodCreate withBuyerExternalIdentifier(String buyerExternalIdentifier) {
        Utils.checkNotNull(buyerExternalIdentifier, "buyerExternalIdentifier");
        this.buyerExternalIdentifier = JsonNullable.of(buyerExternalIdentifier);
        return this;
    }

    /**
     * The merchant reference for this payment method.
     */
    public SEPABankPaymentMethodCreate withBuyerExternalIdentifier(JsonNullable<String> buyerExternalIdentifier) {
        Utils.checkNotNull(buyerExternalIdentifier, "buyerExternalIdentifier");
        this.buyerExternalIdentifier = buyerExternalIdentifier;
        return this;
    }

    /**
     * The merchant identifier for this payment method.
     */
    public SEPABankPaymentMethodCreate withExternalIdentifier(String externalIdentifier) {
        Utils.checkNotNull(externalIdentifier, "externalIdentifier");
        this.externalIdentifier = JsonNullable.of(externalIdentifier);
        return this;
    }

    /**
     * The merchant identifier for this payment method.
     */
    public SEPABankPaymentMethodCreate withExternalIdentifier(JsonNullable<String> externalIdentifier) {
        Utils.checkNotNull(externalIdentifier, "externalIdentifier");
        this.externalIdentifier = externalIdentifier;
        return this;
    }

    /**
     * The IBAN for this SEPA bank account
     */
    public SEPABankPaymentMethodCreate withAccountNumber(String accountNumber) {
        Utils.checkNotNull(accountNumber, "accountNumber");
        this.accountNumber = accountNumber;
        return this;
    }

    /**
     * The BIC for this SEPA bank account
     */
    public SEPABankPaymentMethodCreate withRoutingNumber(String routingNumber) {
        Utils.checkNotNull(routingNumber, "routingNumber");
        this.routingNumber = JsonNullable.of(routingNumber);
        return this;
    }

    /**
     * The BIC for this SEPA bank account
     */
    public SEPABankPaymentMethodCreate withRoutingNumber(JsonNullable<String> routingNumber) {
        Utils.checkNotNull(routingNumber, "routingNumber");
        this.routingNumber = routingNumber;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        SEPABankPaymentMethodCreate other = (SEPABankPaymentMethodCreate) o;
        return 
            Utils.enhancedDeepEquals(this.method, other.method) &&
            Utils.enhancedDeepEquals(this.accountHolder, other.accountHolder) &&
            Utils.enhancedDeepEquals(this.buyerId, other.buyerId) &&
            Utils.enhancedDeepEquals(this.buyerExternalIdentifier, other.buyerExternalIdentifier) &&
            Utils.enhancedDeepEquals(this.externalIdentifier, other.externalIdentifier) &&
            Utils.enhancedDeepEquals(this.scheme, other.scheme) &&
            Utils.enhancedDeepEquals(this.accountNumber, other.accountNumber) &&
            Utils.enhancedDeepEquals(this.routingNumber, other.routingNumber);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            method, accountHolder, buyerId,
            buyerExternalIdentifier, externalIdentifier, scheme,
            accountNumber, routingNumber);
    }
    
    @Override
    public String toString() {
        return Utils.toString(SEPABankPaymentMethodCreate.class,
                "method", method,
                "accountHolder", accountHolder,
                "buyerId", buyerId,
                "buyerExternalIdentifier", buyerExternalIdentifier,
                "externalIdentifier", externalIdentifier,
                "scheme", scheme,
                "accountNumber", accountNumber,
                "routingNumber", routingNumber);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private BankAccountHolder accountHolder;

        private JsonNullable<String> buyerId = JsonNullable.undefined();

        private JsonNullable<String> buyerExternalIdentifier = JsonNullable.undefined();

        private JsonNullable<String> externalIdentifier = JsonNullable.undefined();

        private String accountNumber;

        private JsonNullable<String> routingNumber = JsonNullable.undefined();

        private Builder() {
          // force use of static builder() method
        }


        public Builder accountHolder(BankAccountHolder accountHolder) {
            Utils.checkNotNull(accountHolder, "accountHolder");
            this.accountHolder = accountHolder;
            return this;
        }


        /**
         * The ID of the buyer to attach the method to.
         */
        public Builder buyerId(String buyerId) {
            Utils.checkNotNull(buyerId, "buyerId");
            this.buyerId = JsonNullable.of(buyerId);
            return this;
        }

        /**
         * The ID of the buyer to attach the method to.
         */
        public Builder buyerId(JsonNullable<String> buyerId) {
            Utils.checkNotNull(buyerId, "buyerId");
            this.buyerId = buyerId;
            return this;
        }


        /**
         * The merchant reference for this payment method.
         */
        public Builder buyerExternalIdentifier(String buyerExternalIdentifier) {
            Utils.checkNotNull(buyerExternalIdentifier, "buyerExternalIdentifier");
            this.buyerExternalIdentifier = JsonNullable.of(buyerExternalIdentifier);
            return this;
        }

        /**
         * The merchant reference for this payment method.
         */
        public Builder buyerExternalIdentifier(JsonNullable<String> buyerExternalIdentifier) {
            Utils.checkNotNull(buyerExternalIdentifier, "buyerExternalIdentifier");
            this.buyerExternalIdentifier = buyerExternalIdentifier;
            return this;
        }


        /**
         * The merchant identifier for this payment method.
         */
        public Builder externalIdentifier(String externalIdentifier) {
            Utils.checkNotNull(externalIdentifier, "externalIdentifier");
            this.externalIdentifier = JsonNullable.of(externalIdentifier);
            return this;
        }

        /**
         * The merchant identifier for this payment method.
         */
        public Builder externalIdentifier(JsonNullable<String> externalIdentifier) {
            Utils.checkNotNull(externalIdentifier, "externalIdentifier");
            this.externalIdentifier = externalIdentifier;
            return this;
        }


        /**
         * The IBAN for this SEPA bank account
         */
        public Builder accountNumber(String accountNumber) {
            Utils.checkNotNull(accountNumber, "accountNumber");
            this.accountNumber = accountNumber;
            return this;
        }


        /**
         * The BIC for this SEPA bank account
         */
        public Builder routingNumber(String routingNumber) {
            Utils.checkNotNull(routingNumber, "routingNumber");
            this.routingNumber = JsonNullable.of(routingNumber);
            return this;
        }

        /**
         * The BIC for this SEPA bank account
         */
        public Builder routingNumber(JsonNullable<String> routingNumber) {
            Utils.checkNotNull(routingNumber, "routingNumber");
            this.routingNumber = routingNumber;
            return this;
        }

        public SEPABankPaymentMethodCreate build() {

            return new SEPABankPaymentMethodCreate(
                accountHolder, buyerId, buyerExternalIdentifier,
                externalIdentifier, accountNumber, routingNumber);
        }


        private static final LazySingletonValue<Optional<String>> _SINGLETON_VALUE_Method =
                new LazySingletonValue<>(
                        "method",
                        "\"bank\"",
                        new TypeReference<Optional<String>>() {});

        private static final LazySingletonValue<Optional<String>> _SINGLETON_VALUE_Scheme =
                new LazySingletonValue<>(
                        "scheme",
                        "\"sepa\"",
                        new TypeReference<Optional<String>>() {});
    }
}
