/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.gr4vy.sdk.models.operations.async;

import static com.gr4vy.sdk.operations.Operations.AsyncRequestOperation;

import com.gr4vy.sdk.SDKConfiguration;
import com.gr4vy.sdk.models.components.ThreeDSecureScenarioCreate;
import com.gr4vy.sdk.models.operations.CreateThreeDsScenarioRequest;
import com.gr4vy.sdk.operations.CreateThreeDsScenario;
import com.gr4vy.sdk.utils.Headers;
import com.gr4vy.sdk.utils.Utils;
import java.lang.String;
import java.util.concurrent.CompletableFuture;
import org.openapitools.jackson.nullable.JsonNullable;

public class CreateThreeDsScenarioRequestBuilder {

    private JsonNullable<String> merchantAccountId = JsonNullable.undefined();
    private ThreeDSecureScenarioCreate threeDSecureScenarioCreate;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public CreateThreeDsScenarioRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateThreeDsScenarioRequestBuilder merchantAccountId(String merchantAccountId) {
        Utils.checkNotNull(merchantAccountId, "merchantAccountId");
        this.merchantAccountId = JsonNullable.of(merchantAccountId);
        return this;
    }

    public CreateThreeDsScenarioRequestBuilder merchantAccountId(JsonNullable<String> merchantAccountId) {
        Utils.checkNotNull(merchantAccountId, "merchantAccountId");
        this.merchantAccountId = merchantAccountId;
        return this;
    }

    public CreateThreeDsScenarioRequestBuilder threeDSecureScenarioCreate(ThreeDSecureScenarioCreate threeDSecureScenarioCreate) {
        Utils.checkNotNull(threeDSecureScenarioCreate, "threeDSecureScenarioCreate");
        this.threeDSecureScenarioCreate = threeDSecureScenarioCreate;
        return this;
    }


    private CreateThreeDsScenarioRequest buildRequest() {

        CreateThreeDsScenarioRequest request = new CreateThreeDsScenarioRequest(merchantAccountId,
            threeDSecureScenarioCreate);

        return request;
    }

    public CompletableFuture<CreateThreeDsScenarioResponse> call() {
        
        AsyncRequestOperation<CreateThreeDsScenarioRequest, CreateThreeDsScenarioResponse> operation
              = new CreateThreeDsScenario.Async(sdkConfiguration, _headers);
        CreateThreeDsScenarioRequest request = buildRequest();

        return operation.doRequest(request)
            .thenCompose(operation::handleResponse);
    }
}
