name: Publish SDK
permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write
"on":
  push:
    branches:
      - main
    paths:
      - .speakeasy/gen.lock
  workflow_dispatch: {}
env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
jobs:
  publish:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/sdk-publish.yaml@v15
    with:
      target: java
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      java_gpg_passphrase: ${{ secrets.JAVA_GPG_PASSPHRASE }}
      java_gpg_secret_key: ${{ secrets.JAVA_GPG_SECRET_KEY }}
      ossrh_password: ${{ secrets.OSSRH_PASSWORD }}
      ossrh_username: ${{ secrets.OSSRH_USERNAME }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}
    

  notify:
    needs: publish
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: github.ref == 'refs/heads/main'
        env:
            SLACK_USERNAME: Java SDK 
            SLACK_TITLE: Java SDK
            SLACK_WEBHOOK: ${{ secrets.SLACK_SDK_WEBHOOK_URL }}
            SLACK_CHANNEL: sdk-updates
            SLACK_MSG_AUTHOR: gr4vy-code
            SLACK_ICON_EMOJI: ":gr4vy:"
            SLACK_COLOR: "${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}"
            SLACK_MESSAGE_ON_SUCCESS: "SDK publishing succeeded - `${{ github.event.head_commit.message }}`"
            SLACK_MESSAGE_ON_FAILURE: "SDK publishing failed - `${{ github.event.head_commit.message }}`"
            SLACK_FOOTER: ""

  dispatch:
    needs: publish
    strategy:
      matrix:
        repo:
          - gr4vy/gr4vy-docs-mintlify
    runs-on: ubuntu-latest
    steps:
      - name: Notify SDKs
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: sdk_updated