/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.github.gr4vy.gr4vy_java.models.components;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.github.gr4vy.gr4vy_java.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.Objects;
import org.openapitools.jackson.nullable.JsonNullable;

public class PaymentOptionContextApprovalUI {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("height")
    private JsonNullable<String> height;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("width")
    private JsonNullable<String> width;

    @JsonCreator
    public PaymentOptionContextApprovalUI(
            @JsonProperty("height") JsonNullable<String> height,
            @JsonProperty("width") JsonNullable<String> width) {
        Utils.checkNotNull(height, "height");
        Utils.checkNotNull(width, "width");
        this.height = height;
        this.width = width;
    }
    
    public PaymentOptionContextApprovalUI() {
        this(JsonNullable.undefined(), JsonNullable.undefined());
    }

    @JsonIgnore
    public JsonNullable<String> height() {
        return height;
    }

    @JsonIgnore
    public JsonNullable<String> width() {
        return width;
    }

    public final static Builder builder() {
        return new Builder();
    }    

    public PaymentOptionContextApprovalUI withHeight(String height) {
        Utils.checkNotNull(height, "height");
        this.height = JsonNullable.of(height);
        return this;
    }

    public PaymentOptionContextApprovalUI withHeight(JsonNullable<String> height) {
        Utils.checkNotNull(height, "height");
        this.height = height;
        return this;
    }

    public PaymentOptionContextApprovalUI withWidth(String width) {
        Utils.checkNotNull(width, "width");
        this.width = JsonNullable.of(width);
        return this;
    }

    public PaymentOptionContextApprovalUI withWidth(JsonNullable<String> width) {
        Utils.checkNotNull(width, "width");
        this.width = width;
        return this;
    }

    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PaymentOptionContextApprovalUI other = (PaymentOptionContextApprovalUI) o;
        return 
            Objects.deepEquals(this.height, other.height) &&
            Objects.deepEquals(this.width, other.width);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            height,
            width);
    }
    
    @Override
    public String toString() {
        return Utils.toString(PaymentOptionContextApprovalUI.class,
                "height", height,
                "width", width);
    }
    
    public final static class Builder {
 
        private JsonNullable<String> height = JsonNullable.undefined();
 
        private JsonNullable<String> width = JsonNullable.undefined();
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder height(String height) {
            Utils.checkNotNull(height, "height");
            this.height = JsonNullable.of(height);
            return this;
        }

        public Builder height(JsonNullable<String> height) {
            Utils.checkNotNull(height, "height");
            this.height = height;
            return this;
        }

        public Builder width(String width) {
            Utils.checkNotNull(width, "width");
            this.width = JsonNullable.of(width);
            return this;
        }

        public Builder width(JsonNullable<String> width) {
            Utils.checkNotNull(width, "width");
            this.width = width;
            return this;
        }
        
        public PaymentOptionContextApprovalUI build() {
            return new PaymentOptionContextApprovalUI(
                height,
                width);
        }
    }
}
